<?php
$json2= '{
    "chart": {
        "caption": "Grafik Pengiriman Produksi Oil",
        "subCaption": "Bulan '. $bulanz .'",
        "xAxisName": "Tanggal",
        "yAxisName": "Volume (bbls)",
		"xAxisNameFontSize": "11",
		"yAxisNameFontSize": "11",
		"maxColWidth": "34",
        "bgColor": "#b9b9b9",
        "bgAlpha": "90",		
		"paletteColors": "#0075c2",
        "valueFontColor": "#ffffff",
        "baseFont": "Helvetica Neue,Arial",
        "captionFontSize": "14",
        "subcaptionFontSize": "14",
        "subcaptionFontBold": "0",
		"placeValuesInside": "0",
		"showValues": "0",
		"formatNumber": "1",
		"decimals": "2",
		"formatNumberScale": "0",
        "showShadow": "0",
        "canvasBorderThickness": "1",
        "divlineColor": "#999999",
        "divLineDashed": "1",
        "divlineThickness": "1",
        "divLineDashLen": "1",
        "divLineGapLen": "1",
        "canvasBgColor": "#ffffff",
		"chartLeftMargin": "5",
		"chartTopMargin": "5",
		"chartBottomMargin": "5"		
    },
    "data": [	
		{ "label": "1", "value": "'.$arrKir[0].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "2", "value": "'.$arrKir[1].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "3", "value": "'.$arrKir[2].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "4", "value": "'.$arrKir[3].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "5", "value": "'.$arrKir[4].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "6", "value": "'.$arrKir[5].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "7", "value": "'.$arrKir[6].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "8", "value": "'.$arrKir[7].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "9", "value": "'.$arrKir[8].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "10", "value": "'.$arrKir[9].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "11", "value": "'.$arrKir[10].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "12", "value": "'.$arrKir[11].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "13", "value": "'.$arrKir[12].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "14", "value": "'.$arrKir[13].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "15", "value": "'.$arrKir[14].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "16", "value": "'.$arrKir[15].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "17", "value": "'.$arrKir[16].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "18", "value": "'.$arrKir[17].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "19", "value": "'.$arrKir[18].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "20", "value": "'.$arrKir[19].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "21", "value": "'.$arrKir[20].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "22", "value": "'.$arrKir[21].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "23", "value": "'.$arrKir[22].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "24", "value": "'.$arrKir[23].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "25", "value": "'.$arrKir[24].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "26", "value": "'.$arrKir[25].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "27", "value": "'.$arrKir[26].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "28", "value": "'.$arrKir[27].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "29", "value": "'.$arrKir[28].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "30", "value": "'.$arrKir[29].'", "color": "#ff0000", "Alpha": "70" },
		{ "label": "31", "value": "'.$arrKir[30].'", "color": "#ff0000", "Alpha": "70" },
    ]
}';
$array = json_decode($json1);
$jsonEncodedData = json_encode($array);
$columnChart1 = new FusionCharts("column3D", "Chart-1" , 600, 320, "chart-1", "json", $jsonEncodedData);
$columnChart1->render();

?>
